[workspace]
members = [
  "bidi",
  "bidi/generate",
  "pty",
  "wezterm",
  "wezterm-dynamic",
  "wezterm-blob-leases",
]
resolver = "2"
exclude = [
  "termwiz/codegen"
]

[profile.release]
opt-level = 3
